version: '2'
services:
  nginx:
    image: nginx:latest
    container_name: nginx1
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./src:/src
      - ./config/nginx:/etc/nginx/conf.d
    depends_on:
      - web
    links:
      - web:web

  web:
    build: .
    container_name: jtmain
    command: bash -c "python manage.py makemigrations && python manage.py migrate && gunicorn jtmain.wsgi -b 0.0.0.0:8000"
    depends_on:
      - db
    volumes:
      - ./src:/src

  db:
    image: postgres:latest
    container_name: postgres1
